;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sentence
        beginning-of-visual-line
        c-electric-brace
        c-electric-delete-forward
        c-electric-paren
        c-electric-semi&comma
        dired-next-line
        dired-previous-line
        dired-unmark-backward
        end-of-visual-line
        god-mode-self-insert
        org-backward-paragraph
        org-beginning-of-line
        org-end-of-line
        org-self-insert-command
        undo-redo
        wdired--self-insert
        ))

(setq mc/cmds-to-run-once
      '(
        c-electric-star
        counsel-M-x
        god-local-mode
        ignore
        kmacro-end-and-call-macro
        mouse-buffer-menu
        unmole-mc-mark-next-like-this
        unmole-mc-skip-to-next-like-this
        ))
